There is an online interpreter for Icon located at https://www.calormen.com/jslogo/#

To interpret Logo code, open the .txt file and copy all text into the text box at the bottom of the screen, then hit the 'Run' button to its right.

