draw: triangle.o square.o rectangel.o

triangle.o : triangle.lg
            cc -c triangle.lg
            
square.0 : square.lg
          cc -c square.lg
          
rectangle.o : rectangle.lg
          cc -c rectangle.lg
