draw: triangle.o square.o rectangel.o s.o mirroredRhombus.o

triangle.o : triangle.lg
            cc -c triangle.lg
            
square.0 : square.lg
          cc -c square.lg
          
rectangle.o : rectangle.lg
          cc -c rectangle.lg

s.o : s.lg
          cc -c s.lg
          
mirroredRhombus.o : mirroredRhombus.lg
          cc -c mirroredRhombus.lg
